apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnd-database-api-deployment
spec:
  selector:
    matchLabels:
      app: dnd-database-api
  template:
    metadata:
      labels:
        app: dnd-database-api
    spec:
      containers:
      - name: dnd-database-api
        image: lukaszsmoczynski/dnd-database-api:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: MongoDbSettings__Host
            value: dnd-database-mongo-service
          - name: MongoDbSettings__Username
            value: mongoadmin
          - name: MongoDbSettings__Password
            valueFrom:
              secretKeyRef:
                name: dnd-database-secrets
                key: mongodb-password
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dnd-database-service
spec:
  type: LoadBalancer
  selector:
    app: dnd-database-api
  ports:
  - port: 8080
    targetPort: 80