apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dnd-database-mongo-statefulset
spec:
  serviceName: dnd-database-mongo-service
  selector:
    matchLabels:
      app: dnd-database-mongo
  template:
    metadata:
      labels:
        app: dnd-database-mongo
    spec:
      containers:
      - name: dnd-database-mongo
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: mongoadmin
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dnd-database-secrets
                key: mongodb-password
        volumeMounts:
          - mountPath: /data/db
            name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
#        livenessProbe:
#          httpGet:
#            path: /health/live
#            port: 80
#        readinessProbe:
#          httpGet:
#            path: /health/ready
#            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dnd-database-mongo-service
spec:
  clusterIP: None
  selector:
    app: dnd-database-mongo
  ports:
  - port: 27017
    targetPort: 27017