//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dndDatabaseAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dndDatabaseAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;classes version=&quot;1&quot;&gt;
        ///	&lt;class&gt;
        ///		&lt;name&gt;Barbarian&lt;/name&gt;
        ///		&lt;hitDice&gt;12&lt;/hitDice&gt;
        ///		&lt;descriptions&gt;
        ///			&lt;classDescription&gt;
        ///				A tall human tribesman strides through a blizzard, draped in fur and hefting his axe. He laughs as he charges toward the frost giant who dared poach his peopleâ€™s elk herd.
        ///				A half-orc snarls at the latest challenger to her authority over their savage tribe, ready to break his neck with her bare hands as she did to the last six rivals.
        ///				Frothing at the mouth, a dwarf slam [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string classes {
            get {
                return ResourceManager.GetString("classes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;compendium version=&quot;5&quot;&gt;
        ///	&lt;!-- Spell Attack rolls assume PROF added to roll, not applicable for Ranged while engaged in Melee range --&gt;
        ///	&lt;!-- replaced &quot;:&quot; as intro to list with &quot;.&quot;, and as in-line text with &quot; - &quot; --&gt;
        ///	&lt;!-- after bold w/ : is implemented in app, check &quot;x - x:&quot; (e.g. &quot;Reincarnate&quot;) --&gt;
        ///	&lt;!-- after bold w/ : is implemented in app, check stats table from &quot;Animate Objects&quot; --&gt;
        ///	&lt;!-- after bold w/ : is implemented in app, check &quot;Storm of Vengeance&quot; --&gt;
        ///	&lt;spell&gt;
        ///		&lt;name&gt;Acid Splash&lt;/name&gt;
        /// [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string spells {
            get {
                return ResourceManager.GetString("spells", resourceCulture);
            }
        }
    }
}
